using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using com.igg.hypercontent.runtime;
using com.igg.hypercontent.shared;

namespace com.igg.hypercontent.editor.simulation
{
    /// <summary>
    /// ICatalog implementation for UseAssetDatabase play mode.
    /// Loads the Editor-only catalog JSON generated by EditorCatalogGenerator,
    /// which contains the same address→assetPath mapping as the real build pipeline.
    /// No runtime scanning — fully deterministic, consistent with what a real build would produce.
    /// </summary>
    internal sealed class EditorAssetDatabaseCatalog : ICatalog
    {
        private Dictionary<string, string> _keyToPath;
        private Dictionary<string, string> _guidToPath;
        private bool _isValid;

        public string Version => "editor-simulated";
        public bool IsValid => _isValid;

        /// <summary>
        /// Initialize by loading the Editor catalog JSON.
        /// The source parameter is ignored — catalog path is fixed at EditorCatalogGenerator.CatalogPath.
        /// </summary>
        public bool Initialize(string source)
        {
            _keyToPath = new Dictionary<string, string>(StringComparer.Ordinal);
            _guidToPath = new Dictionary<string, string>(StringComparer.Ordinal);

            string catalogPath = EditorCatalogGenerator.CatalogPath;

            if (!File.Exists(catalogPath))
            {
                HCLogger.LogError(ErrorCode.CATALOG_NOT_FOUND,
                    $"Editor catalog not found at {catalogPath}. " +
                    "Please click 'Update Editor Catalog' on the Overview tab of HyperContent > HyperContent Window.");
                return false;
            }

            try
            {
                string json = File.ReadAllText(catalogPath);
                var data = JsonUtility.FromJson<EditorCatalogData>(json);
                if (data == null || data.entries == null)
                {
                    HCLogger.LogError(ErrorCode.CATALOG_INVALID_FORMAT,
                        "Editor catalog JSON is empty or invalid.");
                    return false;
                }

                foreach (var entry in data.entries)
                {
                    if (!string.IsNullOrEmpty(entry.key) && !_keyToPath.ContainsKey(entry.key))
                        _keyToPath[entry.key] = entry.assetPath;

                    if (!string.IsNullOrEmpty(entry.guid) && !_guidToPath.ContainsKey(entry.guid))
                        _guidToPath[entry.guid] = entry.assetPath;
                }

                _isValid = true;
                HCLogger.LogInfo($"[EditorAssetDatabaseCatalog] Loaded {data.entries.Count} entries from {catalogPath}");
                return true;
            }
            catch (Exception e)
            {
                HCLogger.LogError(ErrorCode.CATALOG_LOAD_FAILED,
                    $"Failed to load Editor catalog: {e.Message}");
                return false;
            }
        }

        public bool TryGetLocations(string address, Type type, out IList<ResourceLocation> locations)
        {
            locations = null;
            if (!_isValid || string.IsNullOrEmpty(address)) return false;

            string assetPath = ResolveAddress(address);
            if (string.IsNullOrEmpty(assetPath)) return false;

            var loc = new ResourceLocation(
                address: address,
                internalId: assetPath,
                providerId: AssetDatabaseProvider.ID,
                resourceType: type);

            locations = new List<ResourceLocation>(1) { loc };
            return true;
        }

        public bool TryGetBundleInfo(string bundleName, out BundleInfo bundleInfo)
        {
            bundleInfo = null;
            return false;
        }

        public IEnumerable<string> GetAllBundleNames()
        {
            return Array.Empty<string>();
        }

        public void Release()
        {
            _keyToPath?.Clear();
            _guidToPath?.Clear();
            _isValid = false;
        }

        private string ResolveAddress(string address)
        {
            // 1. GUID lookup
            if (address.Length == 32 && IsHex(address))
            {
                if (_guidToPath.TryGetValue(address.ToLowerInvariant(), out string path))
                    return path;
            }

            // 2. Key lookup (the primary path — matches marker assetKey)
            if (_keyToPath.TryGetValue(address, out string keyPath))
                return keyPath;

            return null;
        }

        private static bool IsHex(string s)
        {
            foreach (char c in s)
            {
                if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')))
                    return false;
            }
            return true;
        }
    }
}
