using System;
using System.Collections.Generic;

namespace HyperContent
{
    /// <summary>
    /// Catalog schema v2: stringTable + AssetRecord + NameAlias + BundleRecord.
    /// Enables O(log n) lookup by GUID or Name and minimal GC via index-based strings.
    /// Schema ownership: Owner0. Generated by Owner1 build pipeline.
    /// Version: use CatalogSchemaV2.SchemaVersion constant (field removed to avoid redundancy).
    /// </summary>
    [Serializable]
    public class CatalogSchemaV2
    {
        public const int SchemaVersion = 2;

        /// <summary>Hash of catalog content for hot-update detection. byte[] for performance and compact storage.</summary>
        public byte[] catalogHash;

        public long timestamp;

        /// <summary>All strings referenced by index elsewhere. Build-time dedup ensures no duplicate strings (string interning).</summary>
        public string[] stringTable = new string[0];

        /// <summary>Asset records (sorted by guid for binary search). List for dynamic length.</summary>
        public List<AssetRecordEntry> assetRecords = new List<AssetRecordEntry>();

        /// <summary>Name to GUID mapping (sorted by nameHash for binary search). List for dynamic length.</summary>
        public List<NameAliasEntry> nameAliases = new List<NameAliasEntry>();

        /// <summary>Bundle metadata and dependencies. List for dynamic length.</summary>
        public List<BundleRecordEntry> bundleRecords = new List<BundleRecordEntry>();

        [Serializable]
        public class AssetRecordEntry
        {
            /// <summary>Guid type for better performance and memory than string.</summary>
            public Guid guid;
            public int bundleIndex;
            public int assetPathIndex;
        }

        [Serializable]
        public class NameAliasEntry
        {
            public string nameHash;
            public int assetRecordIndex;
        }

        [Serializable]
        public class BundleRecordEntry
        {
            public int bundleNameIndex;
            /// <summary>Bundle file hash (contentHash). string for JSON readability; consider byte[] for runtime.</summary>
            public string bundleHash;
            public long size;
            /// <summary>List to avoid empty-array allocation when no dependencies.</summary>
            public List<int> dependencies = new List<int>();
            /// <summary>Optional: derivable from assetRecords at runtime; kept for fast access.</summary>
            public int assetCount;
        }
    }
}
