using System;
using System.Collections.Generic;

namespace com.igg.hypercontent.runtime
{
    /// <summary>
    /// Catalog schema: stringTable + AssetRecord + NameAlias + BundleRecord.
    /// Enables O(1) Dictionary lookup by GUID or Name and minimal GC via index-based strings.
    /// Schema ownership: Owner0. Generated by Owner1 build pipeline.
    /// </summary>
    [Serializable]
    public class CatalogSchema
    {
        /// <summary>
        /// Binary/catalog JSON format version. Runtime accepts only <see cref="CurrentSchemaVersion"/>; any other value fails load with
        /// <see cref="com.igg.hypercontent.shared.ErrorCode.CATALOG_VERSION_MISMATCH"/> (rebuild and ship a matching catalog).
        /// </summary>
        public int schemaVersion;

        /// <summary>Expected value for <see cref="schemaVersion"/> in serialized catalogs. Bump when breaking schema fields change.</summary>
        public const int CurrentSchemaVersion = 2;

        /// <summary>Index into stringTable for the catalog identity name.</summary>
        public int catalogNameIndex;

        /// <summary>SHA256 hash of catalog content (64-char lowercase hex) for hot-update detection.</summary>
        public string catalogHash;

        public long timestamp;

        /// <summary>All strings referenced by index elsewhere. Build-time dedup ensures no duplicate strings (string interning).</summary>
        public string[] stringTable = new string[0];

        /// <summary>Asset records. List for dynamic length.</summary>
        public List<AssetRecordEntry> assetRecords = new List<AssetRecordEntry>();

        /// <summary>Name-to-GUID alias table. List for dynamic length.</summary>
        public List<NameAliasEntry> nameAliases = new List<NameAliasEntry>();

        /// <summary>Bundle metadata and dependencies. List for dynamic length.</summary>
        public List<BundleRecordEntry> bundleRecords = new List<BundleRecordEntry>();

        [Serializable]
        public class AssetRecordEntry
        {
            /// <summary>32-char lowercase hex GUID.</summary>
            public string guid;
            public int bundleIndex;
            public int assetPathIndex;

            /// <summary>
            /// Asset-level dependency bundles: the minimal, self-contained set of bundle indices
            /// (into <see cref="bundleRecords"/>) needed to load THIS asset, computed at build time from
            /// SBP object-level dependency data. Ordered post-order with the owning bundle LAST, so
            /// <c>BundleAssetExtractor</c> can take the last entry as the primary bundle.
            /// <para/>
            /// <c>null</c> or empty means the catalog carries no asset-level data for this asset; the
            /// runtime fails the load with <see cref="com.igg.hypercontent.shared.ErrorCode.CATALOG_ASSET_DEPS_MISSING"/>
            /// instead of falling back to the owning bundle's full bundle-level closure.
            /// </summary>
            public List<int> dependencyBundles;
        }

        [Serializable]
        public class NameAliasEntry
        {
            /// <summary>Index into stringTable for the original name string (runtime lookup key).</summary>
            public int nameStringIndex;
            /// <summary>SHA256 hex of name; used only at build-time for collision detection, unused at runtime.</summary>
            public string nameHash;
            /// <summary>Index into assetRecords (resolves to GUID).</summary>
            public int guidIndex;
        }

        [Serializable]
        public class BundleRecordEntry
        {
            public int bundleNameIndex;
            /// <summary>Bundle file content hash (SHA256 hex) for incremental update.</summary>
            public string bundleHash;
            public long size;
            public List<int> dependencies = new List<int>();
            /// <summary>Derivable from assetRecords at runtime; kept for fast access.</summary>
            public int assetCount;
            /// <summary>
            /// Content location at runtime. Maps to ContentLocation enum:
            /// 3 = StreamingAssets (shipped with APK, Full Build default),
            /// 2 = Remote (CDN download, Update Build changed bundles).
            /// 0 is treated as StreamingAssets for safety.
            /// </summary>
            public int contentLocation;

            /// <summary>
            /// Bit flags: <see cref="BundleTagFlags"/>. Authoritative source at build time is <b>grouping output</b> (per-bundle metadata from the grouping pipeline).
            /// Until that is wired, catalog generation writes <see cref="BundleTagFlags.None"/> for every bundle (all non-blocking).
            /// </summary>
            public int bundleTagFlags;

            /// <summary>
            /// Index into <c>stringTable</c> for CDN-relative path when <see cref="contentLocation"/> is Remote (after platform folder).
            /// Stored **without** <see cref="NamingRules.BUNDLE_FILE_EXTENSION"/>; <see cref="HttpBundleTransport"/> appends <c>.bundle</c> when resolving URLs.
            /// If negative or out of range, runtime falls back to the bundle name string.
            /// </summary>
            public int remoteRelativePathIndex;
        }
    }

    /// <summary>
    /// Build-time tags for a bundle record. Stored as <c>int</c> on <see cref="CatalogSchema.BundleRecordEntry.bundleTagFlags"/>.
    /// <see cref="Blocking"/> is assigned from grouping data when the build pipeline supplies it; otherwise catalogs use <see cref="None"/>.
    /// </summary>
    [Flags]
    public enum BundleTagFlags
    {
        None = 0,

        /// <summary>
        /// Bundle should be prefetched before gameplay (e.g. batch blocking download). Default is non-blocking.
        /// </summary>
        Blocking = 1,
    }
}
